name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  config-dir: 'ci-configs'

jobs:
  enumerate:
    name: Generate Build Matrix Dynamically
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.enumerate.outputs.configs }}
    steps:
    - uses: actions/checkout@v3
    - name: Enumerate Configs
      id: enumerate
      run: |
        find "${{env.config-dir}}"/ -type f -name 'ghc-*.config' \
          | jq -ncR '[inputs | match("ghc-(.+)\\.config$", .) | .captures[0].string | select(.)]' | tee configs.json
        echo "configs=$(cat configs.json)" >> "${GITHUB_OUTPUT}"
  build:
    name: Build
    needs: [enumerate]
    strategy:
      fail-fast: false
      matrix:
        ghc: ${{fromJSON(needs.enumerate.outputs.configs)}}
    runs-on: ubuntu-latest
    env:
      CABAL: cabal --project-file=ci-configs/ghc-${{matrix.ghc}}.config
    continue-on-error: false

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: false

    - name: Cache ~/.cabal/store
      uses: actions/cache@v2
      env:
        cache-name: cache-cabal-store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', 'cabal-${{matrix.ghc}}.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Cache dist-newstyle
      uses: actions/cache@v2
      env:
        cache-name: cache-dist-newstyle
      with:
        path: "dist-newstyle"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', 'cabal-${{matrix.ghc}}.project') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', 'cabal-${{matrix.ghc}}.project') }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Configure and update
      run: |
        "${CABAL[@]}" v2-configure
        "${CABAL[@]}" v2-update
    - name: Build
      run: |
        "${CABAL[@]}" v2-build
