name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.4.1", "8.6.3", "8.8.2", "8.10.3", "9.0.1", "9.2.5", "9.4.3"]
        experimental: [false]
    runs-on: ubuntu-latest
    env:
      STACK_YAML: "stack-${{ matrix.ghc }}.yaml"
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: '2.9.1'

    - name: Cache Global Stack
      uses: actions/cache@v2
      env:
        cache-name: cache-global-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache Local Stack
      uses: actions/cache@v2
      env:
        cache-name: cache-local-stack
      with:
        path: "**/.stack-work"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies --test --no-run-tests
    - name: Build
      run: stack build
